### ISSUE TITLE
[Bug]: Select / Dropdown auto size

### ISSUE THREAD

**Issue by maelp** [radix-vue/shadcn-vue#114]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Shadcn Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

None

### Steps to reproduce

If I add a custom item, it goes "outside" the button, even if I try to set "h-auto" on the item

<img width="237" alt="image" src="https://github.com/radix-vue/shadcn-vue/assets/15458/b870a17f-295d-40c3-8ed1-4f30723ee1eb">

### Describe the bug

I'd like the button size to auto-adapt, right now I have to know in advance the max size and set for instance "h-16", is it possible to have something adaptive?

**Comment by maelp** [comment]
I actually manage to do it when I use "h-auto" on the SelectTrigger
```
<SelectTrigger :class="cn('h-auto', props.class)">
```

but then for some reason I get this error in my app

```
ResizeObserver loop completed with undelivered notifications.
    at handleError (webpack-internal:///../node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///../node_modules/webpack-dev-server/client/overlay.js:271:7)
```

not sure if it's linked or it's a random error?

but in any case perhaps we could add h-auto (and perhaps min-h-[9] or something) on the select trigger?

**Comment by maelp** [comment]
(it doesn't seem to come from my code because I removed any resizing code, and it still shows... could it come from radix-vue/shadcn?)

**Comment by maelp** [comment]
Perhaps linked to this? https://github.com/radix-ui/primitives/issues/2313

**Comment by maelp** [comment]
Okay I pinpointed the issue:

- it happens if I use a "h-auto" on the SelectTrigger
- if I have elements of different sizes in the selection list
- if I have so many elements that the list goes "outside the screen"

and the error happens when I switch from selecting an element which has a certain size to another element which has a different size

so I guess is probably a radix-vue bug caused by a resize observer on the select trigger position / the size of the dropdown options?

**Comment by maelp** [comment]
(not that if I set a max-h on the SelectGroup like so it works without bug)

```
<SelectGroup class="max-h-60 overflow-y-scroll">
```

**Comment by maelp** [comment]
as a reference, this is the custom GSelect that I'm using

```

<template>
  <Select
    :model-value="props.modelValue"
    @update:modelValue="
      (v) => {
        emits('update:modelValue', v);
      }
    "
  >
    <!-- TODO: ideally we should use :class="cn('h-auto', props.class)" but this cause an issue (see https://github.com/radix-vue/shadcn-vue/issues/114) -->
    <SelectTrigger :class="cn('h-auto', props.class)">
      <SelectValue
        placeholder="Select option"
        class="overflow-hidden whitespace-nowrap truncate"
      ></SelectValue>
    </SelectTrigger>
    <SelectContent>
      <SelectGroup class="max-h-60 overflow-y-scroll">
        <SelectItem
          v-for="item in props.options"
          :key="item.title"
          :value="item.value"
          :class="cn(item.disabled ? 'opacity-50 pointer-events-none' : '')"
        >
          <div class="flex flex-col items-start justify-start">
            <div>
              <GIcon
                :icon="item.icon"
                class="w-4 h-4 mr-1"
                v-if="item.icon"
              ></GIcon>
              <span :class="cn(item.titleClasses)">{{ item.title }}</span>
            </div>
            <div class="flex">
              <!-- add a fake-icon if there is an icon on the item so the slot is aligned -->
              <div class="w-4 mr-1" v-if="item.icon"></div>
              <div class="flex flex-col">
                <div
                  v-if="item.subtitle"
                  :class="
                    cn(
                      'text-xs',
                      item.subtitleType === 'red'
                        ? 'text-red-500'
                        : 'text-muted-foreground'
                    )
                  "
                >
                  {{ item.subtitle }}
                </div>
                <!-- Fix the default Button styling which centers text -->
                <div style="text-align: left !important">
                  <slot :item="item"></slot>
                </div>
              </div>
            </div>
          </div>
        </SelectItem>
      </SelectGroup>
    </SelectContent>
  </Select>
</template>

<style scoped></style>
```

**Comment by maelp** [comment]
I tried to make a link to reproduce the issue on CodeSandbox but didn't manage to make it work (not because there was no bug, but because CodeSandbox had issues with my code that I didn't know how to fix — apparently missing some stuff from "radix-vue")

See my corresponding issue on radix-vue

I guess the problem is linked with the dynamic sizing of the list of items when there are items of varying height, perhaps solvable by using animateRequest in the ResizeObserver, like in the linked issue shown above
