### ISSUE TITLE
wasn't a bug. sry. deleted.

### ISSUE THREAD

**Issue by orenmizr** [radix-vue/shadcn-vue#472]
### Reproduction

http:\\none.yet

### Describe the bug

pasted the code from dashboard number 2 . 
install components one by one (first via vscode extension, second via CLI)
throws error - complains about the tooltip internals:
500
Injection `Symbol(TooltipProviderContext)` not found. Component must be used within `TooltipProvider`

at setup (./node_modules/.pnpm/radix-vue@1.6.2_vue@3.4.21/node_modules/radix-vue/dist/index.js:16209:15)
at callWithErrorHandling (./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19)
at setupStatefulComponent (./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7554:25)
at setupComponent (./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7515:36)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:15)
at Module.ssrRenderComponent (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
at _sfc_ssrRender (./components/ui/tooltip/Tooltip.js:35:31)
at renderComponentSubTree (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:695:9)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:12)

### System Info

```bash
linux, popos

package.json: 

  "dependencies": {
    "@vee-validate/nuxt": "^4.12.6",
    "@vueuse/core": "^10.9.0",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "lucide-vue-next": "^0.364.0",
    "nuxt": "^3.11.1",
    "radix-vue": "^1.6.2",
    "tailwind-merge": "^2.2.2",
    "tailwindcss-animate": "^1.0.7",
    "vaul-vue": "^0.1.0",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.11.4",
    "shadcn-nuxt": "^0.10.2",
    "typescript": "^5.4.3"
  }
}
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by lukepolo** [comment]
@orenmizr what was the issue?

**Comment by orenmizr** [comment]
> @orenmizr what was the issue?

I decided to let it go because it needs more investigation. in the examples try to replace the native form tag with shadcn vue Form and something breaks with submission. tell me what you think

I worked around it with useForm.

**Comment by lukepolo** [comment]
the examples in the docs are missing the ` <TooltipProvider>` wrapper

**Comment by orenmizr** [comment]
i have it on my project. don't think it is related. 
if you look everywhere there is an extensive usage of shadcn Form elements like FormItem etc.. but the root is not  the root  Form tag. it is regular form. https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/examples/forms/components/ProfileForm.vue

was trying to implement as advised - https://www.shadcn-vue.com/docs/components/form.html
