### ISSUE TITLE
[Bug]: Adding number-field creates error 500 'Window not defined' after refresh

### ISSUE THREAD

**Issue by Kuba-Kajderowicz** [radix-vue/shadcn-vue#698]
### Reproduction

add number-field component -> refresh page -> error 500 Window

### Describe the bug

after adding the number-field with the code example from the site, it initially works. But once i refresh the page i receive a error 500: Window not defined.

After removing the compontent and import its fine again and can refresh my page successfully.

Here is the log i get (actual directory removed for privacy):

`at ReactiveEffect.fn (path\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1002:13)
at ReactiveEffect.run (path\node_modules\@vue\reactivity\dist\reactivity.cjs.js:172:19)
at get value [as value] (path\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1014:109)
at unref (path\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1138:29)
at Ne (/path/node_modules/radix-vue/dist/index.js:373:41)
at Be (/path/node_modules/radix-vue/dist/index.js:579:13)
at /path/node_modules/radix-vue/dist/index.js:591:12
at callWithErrorHandling (path\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:203:33)
at getter (path\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:5848:22)
`

### System Info

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.31 GB / 7.79 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.0.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 127.0.6533.89
    Edge: Spartan (44.19041.1266.0), Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.1566
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/github-pnxbg5?file=app.vue
