### ISSUE TITLE
[Bug]: Laravel + Inertia + JetStream install into existing project.

### ISSUE THREAD

**Issue by StaticFX** [radix-vue/shadcn-vue#75]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: /
Package manager: pnpm@8.6.0
Radix Vue version: 0.2.3
Shadcn Vue version: latest?
Vue version: 3.2.41
Nuxt version: /
Nuxt mode: /
Nuxt target: /
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
Laravel version: 9.52
Inertia Version: ^1.0.0
```

### Link to minimal reproduction

/

### Steps to reproduce

Install Shadcn Vue into laravel project without typescript/breeze install, and therefore without tsconfig.json or jsconfig.json

### Describe the bug

/Users/devinfritz/Documents/Dev/PHP/studio/resources/js/components/ui/switch/Switch.vue
8  |  import { cn } from '@/lib/utils'
9  |  
10 |  const props = defineProps<SwitchRootProps & { class?: string }>()
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 |  
12 |  const emits = defineEmits<SwitchRootEmits>()
    at error (/Users/devinfritz/Documents/Dev/PHP/studio/node_modules/vue/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3601:15)
    at processDefineProps (/Users/devinfritz/Documents/Dev/PHP/studio/node_modules/vue/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3658:17)
    at Object.compileScript (/Users/devinfritz/Documents/Dev/PHP/studio/node_modules/vue/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4218:43)
    at resolveScript (/Users/devinfritz/Documents/Dev/PHP/studio/node_modules/@vitejs/plugin-vue/dist/index.cjs:272:31)
    at genScriptCode (/Users/devinfritz/Documents/Dev/PHP/studio/node_modules/@vitejs/plugin-vue/dist/index.cjs:2403:18)
    at transformMain (/Users/devinfritz/Documents/Dev/PHP/studio/node_modules/@vitejs/plugin-vue/dist/index.cjs:2219:54)
    at Object.transform (/Users/devinfritz/Documents/Dev/PHP/studio/node_modules/@vitejs/plugin-vue/dist/index.cjs:2702:16)
    at file:///Users/devinfritz/Documents/Dev/PHP/studio/node_modules/rollup/dist/es/shared/node-entry.js:25419:40

### Expected behavior

Working

**Comment by StaticFX** [comment]
Sorry for not providing a link, but it is almost impossible to setup a laravel install the same way on an online editor

**Comment by zernonia** [comment]
Thanks for the info @StaticFX . This might be issue with Vue 3.2 not supporting the types properly. We had idea of parsing the types into Vue compatible `defineProps`.

**Comment by zernonia** [comment]
@StaticFX  I believe updating Vue to `>3.3` solved the issue right?

**Comment by rodrigo-fantuci** [comment]
@zernonia Just to let you know, I'm still having the same problem after updating vue to `3.3.8` in a project without typescript. Is there another possible fix for this?

**Comment by rodrigo-fantuci** [comment]
@zernonia I'm still having the same problem after updating vue to `3.3.8` in a project without typescript. Is there another possible fix for this?

**Comment by sadeghbarati** [comment]
Is the problem exists still? @StaticFX @rodrigo-fantuci

**Comment by hrynevychroman** [comment]
I think that minimal reproduction on Codesandbox will help to fix this error 🙂

**Comment by rodrigo-fantuci** [comment]
@sadeghbarati After updating to Vue 3.4 its now fixed for me 👍
