### ISSUE TITLE
[Bug]:  Popover - Extraneous non-props attributes were passed.

### ISSUE THREAD

**Issue by sugoidesune** [radix-vue/shadcn-vue#793]
### Reproduction

https://stackblitz.com/edit/github-25jj82

### Describe the bug

The Popover component is creating a warning.
- Latest nuxt
- latest shadcn
- Popover example from website

```
 [Vue warn]: Extraneous non-props attributes (data-v-inspector) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
  at <PopperRoot data-v-inspector="app.vue:6:5" >
  at <PopoverRoot onUpdate:open=fn data-v-inspector="app.vue:6:5" >
  at <Popover data-v-inspector="app.vue:6:5" >
  at <App data-v-inspector="node_modules/nuxt/dist/app/components/nuxt-root.vue:16:5" >
  at <NuxtRoot>
```

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 3.70 GB / 15.70 GB
  Binaries:
    Node: 22.1.0 - ~\AppData\Local\Volta\tools\image\node\22.1.0\node.EXE
    Yarn: 3.3.0 - ~\AppData\Local\Volta\tools\image\yarn\3.3.0\bin\yarn.CMD
    npm: 10.7.0 - ~\AppData\Local\Volta\tools\image\node\22.1.0\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vueuse/core: ^11.1.0 => 11.1.0
    nuxt: ^3.13.0 => 3.13.2
    radix-vue: ^1.9.6 => 1.9.6
    shadcn-nuxt: ^0.10.4 => 0.10.4
    vue: latest => 3.5.10
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by sugoidesune** [comment]
Just now thought about dev-tools possibly causing this and it's actually dev-tools... 🤦

**Comment by jonasfroeller** [comment]
@sugoidesune I disabled them, but I still get this warning...

**Comment by ghost** [comment]
me too, but is in dropdown
