### ISSUE TITLE
[Bug]: Following Nuxt installation instructions currently broken due to Fontawesome issue.

### ISSUE THREAD

**Issue by rogadev** [radix-vue/shadcn-vue#803]
### Reproduction

See description

### Describe the bug

Following the steps [here](https://www.shadcn-vue.com/docs/installation/nuxt.html), step 2 produces the following error:

```bash
$ npx nuxi@latest module add tailwindcss

 ERROR  [GET] "https://npm.fontawesome.com/@nuxtjs/tailwindcss/latest": 401 Unauthorized                                              8:39:48 a.m.

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (/C:/Users/ryanr/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.b88e7b0f.mjs:340:15)
  at async resolveModule (/C:/Users/ryanr/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:262:15)
  at async Object.setup (/C:/Users/ryanr/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:136:15)
  at async runCommand$1 (/C:/Users/ryanr/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1620:5)
  at async runCommand$1 (/C:/Users/ryanr/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runCommand$1 (/C:/Users/ryanr/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runMain$1 (/C:/Users/ryanr/AppData/Local/npm-cache/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1777:7) 
  ```
  
  This is an issue that crops up from time to time with the Nuxt module installation of Tailwind. There is a simple workaround which I will submit a pull request to expand upon.

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 69.78 GB / 79.94 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    nuxt: ^3.13.2 => 3.13.2
    vue: latest => 3.5.11
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by rogadev** [comment]
Linking the PR [here](https://github.com/unovue/shadcn-vue/pull/804).
