### ISSUE TITLE
[Bug]: BarChart Legend Display Issue: Misaligned Indicator and Non-Reactive Legends

### ISSUE THREAD

**Issue by tberk** [radix-vue/shadcn-vue#888]
### Reproduction

https://www.shadcn-vue.com/docs/charts/bar

### Describe the bug

When using the BarChart component, there are multiple issues with the legends:

1.  **Misalignment on First Load:**

    -   On the initial load, legend items are displayed within a button component, but the indicator dot (used to denote color) is misaligned and out of place.
2.  **Style Change on Click:**

    -   Clicking a legend item changes its UI style unexpectedly, diverging from the original style setup.
3.  **Incorrect Button Size Definition:**

    -   In `ChartLegend.vue`, the button size is set to `xs`, but the button component itself does not support an `xs` size.

```typescript
onMounted(() => {
  const selector = `.${BulletLegend.selectors.item}`
  nextTick(() => {
    const elements = elRef.value?.querySelectorAll(selector)
    const classes = buttonVariants({ variant: 'ghost', size: 'xs' }).split(' ')
    elements?.forEach(el => el.classList.add(...classes, '!inline-flex', '!mr-2'))
  })
})
```

4.  **Legends Are Not Reactive:**

    -   While other parts of the BarChart component update as expected, the legend items do not react to changes. This could be due to the fact that `legendItems` is defined with `ref` in `BarChart.vue`, as shown below:

```typescript
const legendItems = ref<BulletLegendItemInterface[]>(props.categories.map((category, i) => ({
  name: category,
  color: colors.value[i],
  inactive: false,
})))
```

**Expected Behavior:**

-   The indicator dot should be correctly aligned on the first load.
-   Clicking on a legend item should not alter its style unexpectedly.
-   The button size should align with available sizes or be adjusted for consistent styling.
-   Legend items should be reactive to data changes in the BarChart component.

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 34.40 GB / 63.75 GB
  Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by AloisH** [comment]
should be fixied by this https://github.com/unovue/shadcn-vue/pull/1125
can you have a look ?

**Comment by tberk** [comment]
I did a fresh install to test, but I’m getting an error when trying to install this component. Other components install without any issues. 🤔

Legends UI issue seems to be resolved (as I can see from the official docs). I also want to test the reactivity, I don't think it is addressed here tho.

```
PS D:\Projects\nuxt-shadcn> pnpm dlx shadcn-vue@latest add chart-bar
⠧ Checking registry.                                                                                                                                                              
          13:39:39

this is error:                                                                                                                                                          13:39:39  

    at /C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:1102:17
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:1101:26
    at async Promise.all (index 0)
    at async fetchRegistry (/C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:1098:21)
    at async resolveDependencies (/C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:1208:24)
    at async resolveRegistryDependencies (/C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:1223:3)
    at async registryResolveItemsTree (/C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:1147:40)
    at async addProjectComponents (/C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:2353:16)
    at async addComponents (/C:/Users/****/AppData/Local/pnpm-cache/dlx/eba9e6c3357f4e1b7269301a5400907f13b9ca7c97212be12042798e95b618ad/1960091c175-2ca0/node_modules/.pnpm/shadcn-vue@2.0.0_@vitest+ui_a3d6e17e7e21f1f641da284382e28a28/node_modules/shadcn-vue/dist/index.js:2347:10)

 ERROR
```

**Comment by AloisH** [comment]
With the version 2 the chart has been drop and will move to a separate repository. you can try the latest version of shadcn-vue 1

**Comment by tberk** [comment]
Created a reproduction using the v1: https://stackblitz.com/~/github.com/tberk/shadcn-v1

Issues seems to persisting.

**Comment by AloisH** [comment]
I create a PR with the latest v1 version of shadcn and it is currently working: https://github.com/tberk/shadcn-v1/pull/1
https://stackblitz.com/~/github.com/tberk/shadcn-v1?file=components.json

**Comment by tberk** [comment]
Oh I see now, labels seem to be fixed ui-wise, thanks sir.

The reactivity problem persists tho, should it be an another issue?

**Comment by AloisH** [comment]
what is the reactivity issue ?

**Comment by tberk** [comment]
> 4\. **Legends Are Not Reactive:**
>     
>     * While other parts of the BarChart component update as expected, the legend items do not react to changes. This could be due to the fact that `legendItems` is defined with `ref` in `BarChart.vue`, as shown below:
> ```ts
>const legendItems = ref<BulletLegendItemInterface[]>(props.categories.map((category, i) => ({
>   name: category,
>   color: colors.value[i],
>   inactive: false,
> })))
> ```

The legends (top right part) do not react to changes but the bars do. For example after adding a new category, labels do not update but data does. In the original library when same change applied legends update too.

In my demo repo you can see the problem after clicking the button "-> Update Categories".

Here's a video of it.

https://github.com/user-attachments/assets/3f55fe03-0e92-4a7c-8c6e-193727d8513a

**Comment by AloisH** [comment]
Oh I see I will try to have a look at it tomorrow

**Comment by zernonia** [comment]
Closing as we deprecated the BarChart
