### ISSUE TITLE
[Feature]: Tailwind 4.0 Beta and running without @nuxtjs/tailwindcss

### ISSUE THREAD

**Issue by marpe** [radix-vue/shadcn-vue#979]
### Describe the feature

I wanted to test out the tailwind 4.0 beta by using their `@tailwindcss/vite` plugin instead of using `@nuxtjs/tailwindcss` but `shadcn-vue` is preventing nuxt from starting:

```js
 ERROR  Cannot start nuxt:  Could not load @nuxtjs/tailwindcss. Is it installed?                                  4:39:09 AM

    at loadNuxtModuleInstance (/C:/dev/kotoba/node_modules/.pnpm/@nuxt+kit@3.15.0_magicast@0.3.5_rollup@4.29.1/node_modules/@nuxt/kit/dist/index.mjs:2470:11)
    at async installModule (/C:/dev/kotoba/node_modules/.pnpm/@nuxt+kit@3.15.0_magicast@0.3.5_rollup@4.29.1/node_modules/@nuxt/kit/dist/index.mjs:2388:67)
    at async setup (/C:/dev/kotoba/node_modules/.pnpm/shadcn-nuxt@0.11.3_magicast@0.3.5_rollup@4.29.1/node_modules/shadcn-nuxt/dist/module.mjs:45:5)
    at async normalizedModule (/C:/dev/kotoba/node_modules/.pnpm/@nuxt+kit@3.15.0_magicast@0.3.5_rollup@4.29.1/node_modules/@nuxt/kit/dist/index.mjs:2139:17)
    at async installModule (/C:/dev/kotoba/node_modules/.pnpm/@nuxt+kit@3.15.0_magicast@0.3.5_rollup@4.29.1/node_modules/@nuxt/kit/dist/index.mjs:2396:95)
    at async initNuxt (/C:/dev/kotoba/node_modules/.pnpm/nuxt@3.15.0_@parcel+watcher@2.5.0_@types+node@22.10.2_db0@0.2.1_drizzle-orm@0.38.3_pg@8.13.1__yhgjblmr6eemhjawogsloaorsa/node_modules/nuxt/dist/index.mjs:5275:5)
    at async NuxtDevServer._load (/C:/Users/marpe/AppData/Local/pnpm-cache/dlx/dyrtvgyweevirrawizpndprwvi/19400ea7a27-d75ec/node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/chunks/dev2.mjs:1888:5)
    at async NuxtDevServer.load (/C:/Users/marpe/AppData/Local/pnpm-cache/dlx/dyrtvgyweevirrawizpndprwvi/19400ea7a27-d75ec/node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/chunks/dev2.mjs:1822:7)
    at async NuxtDevServer.init (/C:/Users/marpe/AppData/Local/pnpm-cache/dlx/dyrtvgyweevirrawizpndprwvi/19400ea7a27-d75ec/node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/chunks/dev2.mjs:1817:5)
    at async Object.run (/C:/Users/marpe/AppData/Local/pnpm-cache/dlx/dyrtvgyweevirrawizpndprwvi/19400ea7a27-d75ec/node_modules/.pnpm/nuxi@3.17.2/node_modules/nuxi/dist/chunks/dev-child.mjs:110:5)
```
    
 Would it be possible to remove this dependency or work around it?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by chz** [comment]
+1

**Comment by kknono** [comment]
+1

**Comment by ManUtopiK** [comment]
Also, I use shadcn-vue with unocss, and it's annoying to load tailwindcss as I don't need it.
Maybe adding a module option to enable/disable at [this line](https://github.com/unovue/shadcn-vue/blob/e532d30244e5ce333a2387ae0da336212815f7fb/packages/module/src/module.ts#L63) could do the trick ?

**Comment by janvorisek** [comment]
+1

**Comment by sap471** [comment]
+1

**Comment by 4EZR** [comment]
+1

**Comment by memic84** [comment]
+1

**Comment by Bogdoing** [comment]
+ 1

**Comment by fmineo** [comment]
+1

**Comment by zernonia** [comment]
We've removed auto install of `color-mode` and `tailwind` module in latest `shadcn-nuxt`. This should allow dev to have greater control over the version.

As for tw v4, please follow https://github.com/unovue/shadcn-vue/issues/1076
